# Secret Scanning Configuration
# Exclude test files with intentional secrets

paths-ignore:
  - 'tests/secret-detection/baseline/**'
  - 'tests/secret-detection/results/**'
  - 'tests/**/test-*.py'
  - 'tests/**/test-*.js'
  - 'tests/**/.env.test'
  - 'tests/**/config.yaml'
