# =============================================================================
# .github/workflow-compliance.yml — NFR-5.6 Compliance Allow-list
# =============================================================================
# Intentional exceptions to validate-workflow-compliance.sh checks.
# Each exception requires a file, constraint code, and justification.
#
# Constraint codes:
#   C1 — npm lock file required
#   C2 — no secrets.* in if: conditions
#   C3 — no markdown at column 0 in block scalars
#   C4 — no bot commit loop (push paths overlap git add paths)
#   C5 — protected branch push must have || echo fallback
#   C6 — unique concurrency groups
#   C7 — actions/deploy-pages must have continue-on-error: true
#   C8 — paid org tools (gitleaks-action) must have continue-on-error: true
#
# To add an exception:
#   - file: exact-workflow-filename.yml
#     constraint: C5
#     justification: "Reason this exception is intentional and safe"
#     approved_by: jorge
#     date: YYYY-MM-DD
# =============================================================================

exceptions: []
