# =============================================================================
# .secrets-manifest.yml — Planned Secret Declarations (FR-10.2)
# =============================================================================
# Secrets listed here are "planned" — they are intended to be configured
# before deployment but may not yet exist. The secret-reference-audit will
# flag them as WARNING (not ERROR), allowing PRs to pass while the secret
# is pending configuration.
#
# Once a secret is configured in the repository, it can be removed from
# this file (the audit will find it via gh secret list).
#
# Format:
#   - name: SECRET_NAME
#     purpose: "What this secret is used for"
#     owner: "Who is responsible for configuring it"
#     needed_by: YYYY-MM-DD
# =============================================================================

planned:
  - name: NOTIFICATION_EMAIL
    purpose: "SMTP sender address for workflow failure notifications"
    owner: jorge
    needed_by: "2026-03-01"

  - name: NOTIFICATION_EMAIL_PASSWORD
    purpose: "SMTP password for workflow failure notifications"
    owner: jorge
    needed_by: "2026-03-01"

  - name: TEAM_EMAIL
    purpose: "Recipient address for workflow failure notifications"
    owner: jorge
    needed_by: "2026-03-01"

  - name: OPENAI_API_KEY
    purpose: "OpenAI API key for AI dashboard data enrichment"
    owner: jorge
    needed_by: "2026-03-15"

  - name: ANTHROPIC_API_KEY
    purpose: "Claude API key for FR-9.2 CI log analysis and failure classification"
    owner: jorge
    needed_by: "2026-03-01"
