#!/bin/bash

# Autonomous Implementation Environment Initialization
# Generated by: run-autonomous-implementation workflow
# Date: TIMESTAMP

set -euo pipefail

# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME="PROJECT_NAME"
PROJECT_FOLDER="PROJECT_FOLDER"

# ============================================================
# PREREQUISITE CHECKS
# ============================================================

echo "Checking prerequisites..."

# Check Git
if ! command -v git &>/dev/null; then
    echo "❌ ERROR: Git not found"
    echo "   Install: apt-get install git"
    exit 1
fi
echo "✓ Git available: $(git --version | head -1)"

# Check GitHub CLI
if ! command -v gh &>/dev/null; then
    echo "❌ ERROR: GitHub CLI (gh) not found"
    echo "   Install: https://cli.github.com/"
    exit 2
fi
echo "✓ GitHub CLI available: $(gh --version | head -1)"

# Check jq
if ! command -v jq &>/dev/null; then
    echo "❌ ERROR: jq not found"
    echo "   Install: apt-get install jq"
    exit 3
fi
echo "✓ jq available: $(jq --version)"

# Check xmllint
if ! command -v xmllint &>/dev/null; then
    echo "❌ ERROR: xmllint not found"
    echo "   Install: apt-get install libxml2-utils"
    exit 4
fi
echo "✓ xmllint available: $(xmllint --version 2>&1 | head -1)"

echo ""
echo "✓ All prerequisites met"
echo ""

# ============================================================
# DIRECTORY SETUP
# ============================================================

echo "Setting up project directories..."

cd "$PROJECT_FOLDER" || exit 5

# Create subdirectories if needed
mkdir -p outputs
mkdir -p logs
mkdir -p scripts
mkdir -p prompts

echo "✓ Project directories ready"
echo ""

# ============================================================
# GIT REPOSITORY CHECK
# ============================================================

echo "Checking git repository..."

if [[ ! -d ".git" ]]; then
    echo "❌ ERROR: Not a git repository"
    echo "   Initialize: git init"
    exit 6
fi

echo "✓ Git repository: $(git rev-parse --show-toplevel)"
echo ""

# ============================================================
# ENVIRONMENT READY
# ============================================================

echo "═══════════════════════════════════════════════════════"
echo "  ENVIRONMENT INITIALIZED"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Project: $PROJECT_NAME"
echo "Location: $PROJECT_FOLDER"
echo ""
echo "Ready for autonomous implementation."
echo ""
echo "Start implementation:"
echo "  /bmad-bmm-run-autonomous-implementation"
echo ""
