#!/usr/bin/env python3
"""
Seven Fortunas Skill Creator with Fuzzy Matching Duplicate Prevention
Implements FR-3.4: Skill Governance (Prevent Proliferation)

Features:
- Search existing skills before creating new (fuzzy matching)
- Usage tracking integration
- Prevents duplicate skill creation
- Generates skill YAML with validation
"""

import sys
import os
import json
import argparse
import re
from difflib import SequenceMatcher
from datetime import datetime
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
COMMANDS_DIR = PROJECT_ROOT / ".claude" / "commands"
SKILLS_REGISTRY = COMMANDS_DIR / "skills-registry.yaml"
USAGE_LOG = COMMANDS_DIR / ".skill-usage.log"


def load_existing_skills():
    """Load all existing skill names and descriptions."""
    skills = {}

    # Search for all .md files in skill directories
    for skill_file in COMMANDS_DIR.rglob("*.md"):
        # Skip special files
        if skill_file.name in ["README.md", "CHANGELOG.md"]:
            continue

        skill_name = skill_file.stem

        # Extract description from frontmatter
        description = ""
        try:
            with open(skill_file, 'r') as f:
                content = f.read()
                # Look for description in frontmatter
                if 'description:' in content:
                    match = re.search(r'description:\s*["\']?([^"\'\n]+)["\']?', content)
                    if match:
                        description = match.group(1)
                # Alternative: look in header
                if not description:
                    lines = content.split('\n')
                    for i, line in enumerate(lines):
                        if line.startswith('# '):
                            description = line[2:].strip()
                            break
        except Exception:
            pass

        skills[skill_name] = {
            'path': str(skill_file),
            'description': description
        }

    return skills


def fuzzy_match(search_term, target, threshold=0.6):
    """
    Fuzzy match using SequenceMatcher.
    Returns similarity ratio (0.0 to 1.0).
    """
    # Normalize for comparison
    search_lower = search_term.lower()
    target_lower = target.lower()

    ratio = SequenceMatcher(None, search_lower, target_lower).ratio()
    return ratio >= threshold, ratio


def search_similar_skills(skill_name, description="", existing_skills=None):
    """
    Search for similar existing skills using fuzzy matching.
    Returns list of similar skills with match scores.
    """
    if existing_skills is None:
        existing_skills = load_existing_skills()

    similar = []

    # Search by name (higher threshold)
    for skill_id, skill_info in existing_skills.items():
        is_match, score = fuzzy_match(skill_name, skill_id, threshold=0.6)
        if is_match:
            similar.append({
                'id': skill_id,
                'description': skill_info['description'],
                'name_score': score,
                'type': 'name'
            })

    # Search by description (if provided)
    if description:
        for skill_id, skill_info in existing_skills.items():
            # Skip if already found by name
            if any(s['id'] == skill_id for s in similar):
                continue

            skill_desc = skill_info['description']
            if skill_desc:
                is_match, score = fuzzy_match(description, skill_desc, threshold=0.5)
                if is_match:
                    similar.append({
                        'id': skill_id,
                        'description': skill_info['description'],
                        'desc_score': score,
                        'type': 'description'
                    })

    # Sort by score (descending)
    similar.sort(
        key=lambda x: x.get('name_score', 0) + x.get('desc_score', 0),
        reverse=True
    )

    return similar


def validate_skill_name(skill_name):
    """Validate skill name format."""
    # Must start with category prefix
    valid_prefixes = ['7f-', 'bmad-bmm-', 'bmad-bmb-', 'bmad-cis-', 'bmad-agent-']

    if not any(skill_name.startswith(p) for p in valid_prefixes):
        return False, f"Skill name must start with: {', '.join(valid_prefixes)}"

    # Must be lowercase with hyphens only
    if not re.match(r'^[a-z0-9-]+$', skill_name):
        return False, "Skill name must contain only lowercase letters, numbers, and hyphens"

    return True, ""


def create_skill_file(skill_name, description, tags, category_path):
    """Create skill file with proper frontmatter."""
    timestamp = datetime.utcnow().isoformat() + "Z"

    content = f"""---
description: "{description}"
tags: {json.dumps(tags)}
created_at: "{timestamp}"
source: "Generated by create-skill.py"
status: "active"
---

# {skill_name}

{description}

## Usage

\\`\\`\\`bash
/{skill_name}
\\`\\`\\`

## Implementation

[To be implemented]

---

**Status:** MVP (Placeholder - Implementation pending)
"""

    skill_file = category_path / f"{skill_name}.md"

    # Ensure directory exists
    skill_file.parent.mkdir(parents=True, exist_ok=True)

    with open(skill_file, 'w') as f:
        f.write(content)

    return str(skill_file)


def log_skill_usage(skill_name):
    """Log skill creation to usage tracker."""
    try:
        timestamp = datetime.utcnow().isoformat() + "Z"
        user = os.environ.get('USER', 'unknown')
        cwd = os.getcwd()

        with open(USAGE_LOG, 'a') as f:
            f.write(f"{timestamp}|{skill_name}|{user}|{cwd}\n")
    except Exception as e:
        print(f"Warning: Could not log usage: {e}", file=sys.stderr)


def confirm_creation(skill_name, description, similar_skills):
    """Ask user for confirmation before creating skill."""
    if similar_skills:
        print("\n⚠️  WARNING: Similar skills found:\n")
        print("These existing skills may provide similar functionality:")
        for i, skill in enumerate(similar_skills[:5], 1):
            print(f"  {i}. {skill['id']}")
            if skill['description']:
                print(f"     {skill['description']}")
            score = skill.get('name_score', 0) + skill.get('desc_score', 0)
            print(f"     Similarity: {score*100:.0f}%")
        print()

    print(f"New skill: {skill_name}")
    print(f"Description: {description}")
    print(f"Category path: {COMMANDS_DIR}/[category]/{skill_name}.md")
    print()

    response = input("Create skill? (yes/no): ").strip().lower()
    return response in ['yes', 'y']


def interactive_mode():
    """Interactive mode for creating skills."""
    print("\n=== Seven Fortunas Skill Creator ===\n")

    # Get skill name
    while True:
        skill_name = input("Skill name (e.g., 7f-my-skill): ").strip()
        if not skill_name:
            print("Skill name cannot be empty.")
            continue

        valid, error = validate_skill_name(skill_name)
        if not valid:
            print(f"Invalid name: {error}")
            continue

        # Check if skill already exists
        if any(s for s in load_existing_skills() if s == skill_name):
            print(f"ERROR: Skill '{skill_name}' already exists!")
            continue

        break

    # Get description
    description = input("Description: ").strip()
    if not description:
        description = "[No description provided]"

    # Get tags
    tags_input = input("Tags (comma-separated, optional): ").strip()
    tags = [t.strip() for t in tags_input.split(',')] if tags_input else []

    # Search for similar skills
    existing = load_existing_skills()
    similar = search_similar_skills(skill_name, description, existing)

    # Ask for confirmation
    if not confirm_creation(skill_name, description, similar):
        print("Skill creation cancelled.")
        return False

    # Determine category
    if skill_name.startswith('7f-'):
        category_path = COMMANDS_DIR / '7f'
    elif skill_name.startswith('bmad-bmm-'):
        category_path = COMMANDS_DIR / 'bmm'
    elif skill_name.startswith('bmad-bmb-'):
        category_path = COMMANDS_DIR / 'bmb'
    elif skill_name.startswith('bmad-cis-'):
        category_path = COMMANDS_DIR / 'cis'
    elif skill_name.startswith('bmad-agent-'):
        # Determine module from agent name
        if 'bmm' in skill_name:
            category_path = COMMANDS_DIR / 'bmm'
        elif 'bmb' in skill_name:
            category_path = COMMANDS_DIR / 'bmb'
        elif 'cis' in skill_name:
            category_path = COMMANDS_DIR / 'cis'
        else:
            category_path = COMMANDS_DIR / '7f'
    else:
        print(f"ERROR: Cannot determine category for {skill_name}")
        return False

    # Create skill
    try:
        skill_file = create_skill_file(skill_name, description, tags, category_path)
        print(f"\n✅ Skill created: {skill_file}")

        # Log usage
        log_skill_usage(skill_name)

        return True
    except Exception as e:
        print(f"\n❌ Error creating skill: {e}")
        return False


def spec_mode(spec_file):
    """Create skill from YAML/JSON specification."""
    try:
        import yaml
    except ImportError:
        print("ERROR: PyYAML required for spec mode. Install: pip install pyyaml")
        return False

    try:
        with open(spec_file, 'r') as f:
            spec = yaml.safe_load(f)

        skill_name = spec['skill']['name']
        description = spec['skill'].get('description', '[No description]')
        tags = spec['skill'].get('tags', [])

        # Validate
        valid, error = validate_skill_name(skill_name)
        if not valid:
            print(f"Invalid skill name: {error}")
            return False

        # Check for duplicates
        existing = load_existing_skills()
        similar = search_similar_skills(skill_name, description, existing)

        if similar and not confirm_creation(skill_name, description, similar):
            print("Skill creation cancelled.")
            return False

        # Create skill
        if skill_name.startswith('7f-'):
            category_path = COMMANDS_DIR / '7f'
        else:
            print(f"ERROR: Spec mode only supports 7f- skills currently")
            return False

        skill_file = create_skill_file(skill_name, description, tags, category_path)
        print(f"✅ Skill created: {skill_file}")

        log_skill_usage(skill_name)
        return True

    except Exception as e:
        print(f"ERROR: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description='Seven Fortunas Skill Creator with Duplicate Prevention'
    )
    parser.add_argument('--spec', help='Create from YAML specification file')
    parser.add_argument('--name', help='Skill name (requires --description)')
    parser.add_argument('--description', help='Skill description (requires --name)')
    parser.add_argument('--tags', help='Comma-separated tags')
    parser.add_argument('--search', help='Search for similar skills without creating')
    parser.add_argument('--list', action='store_true', help='List all existing skills')

    args = parser.parse_args()

    # List mode
    if args.list:
        print("\n=== Existing Skills ===\n")
        skills = load_existing_skills()
        for skill_id in sorted(skills.keys()):
            skill = skills[skill_id]
            desc = skill['description'][:60] if skill['description'] else "[No description]"
            print(f"  {skill_id:40} {desc}")
        print(f"\nTotal: {len(skills)} skills\n")
        return True

    # Search mode
    if args.search:
        print(f"\n=== Searching for: {args.search} ===\n")
        skills = load_existing_skills()
        similar = search_similar_skills(args.search, '', skills)
        if similar:
            for skill in similar[:5]:
                print(f"  {skill['id']}")
                if skill['description']:
                    print(f"    {skill['description']}")
        else:
            print("  (No similar skills found)")
        print()
        return True

    # Quick create mode
    if args.name and args.description:
        skill_name = args.name
        description = args.description
        tags = [t.strip() for t in args.tags.split(',')] if args.tags else []

        valid, error = validate_skill_name(skill_name)
        if not valid:
            print(f"ERROR: {error}")
            return False

        existing = load_existing_skills()
        similar = search_similar_skills(skill_name, description, existing)

        if similar:
            print("Similar skills found:")
            for skill in similar[:3]:
                print(f"  - {skill['id']}")
            # In quick mode, still ask for confirmation
            if not confirm_creation(skill_name, description, similar):
                return False

        if skill_name.startswith('7f-'):
            category_path = COMMANDS_DIR / '7f'
        else:
            print("ERROR: Quick mode only supports 7f- skills")
            return False

        try:
            skill_file = create_skill_file(skill_name, description, tags, category_path)
            print(f"✅ Skill created: {skill_file}")
            log_skill_usage(skill_name)
            return True
        except Exception as e:
            print(f"ERROR: {e}")
            return False

    # Spec mode
    if args.spec:
        return spec_mode(args.spec)

    # Interactive mode
    return interactive_mode()


if __name__ == '__main__':
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\nCancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)
