#!/usr/bin/env bash
# =============================================================================
# validate-and-fix-workflow.sh — FR-10.4 Autonomous Agent Workflow Validation
# =============================================================================
# Validates workflows generated by autonomous agents and applies auto-fixes
# for common violations (C5: bare git push).
#
# Usage:
#   ./scripts/validate-and-fix-workflow.sh <workflow-file>
#
# Exit codes:
#   0 = pass (validated successfully, with or without fixes)
#   1 = fail (unfixable violations remain)
#   2 = warnings only (no errors)
#
# Auto-fix coverage:
#   - C5: bare git push → add || echo "skipped - protected branch"
#
# NOT auto-fixed:
#   - C2: secrets.* in if: → REPORTED as error, never auto-fixed.
#     Rationale: Removing a secret-conditional guard is a security-relevant
#     change. Auto-converting it to continue-on-error:true silently removes
#     the security guard and allows the step to run unconditionally, which
#     can expose credentials or run deployment steps without authorization.
#     This class of violation MUST be fixed manually by a human reviewer.
#
# Other constraints escalate to blocked (manual intervention required).
# =============================================================================

set -uo pipefail

WORKFLOW_FILE="$1"

# MED-002: Use SCRIPT_DIR-relative path instead of hardcoded absolute path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VALIDATOR_PATH="$SCRIPT_DIR/validate-workflow-compliance.sh"

if [[ ! -f "$WORKFLOW_FILE" ]]; then
    echo "Error: Workflow file not found: $WORKFLOW_FILE"
    exit 1
fi

if [[ ! -f "$VALIDATOR_PATH" ]]; then
    echo "Error: Validator not found: $VALIDATOR_PATH"
    exit 1
fi

echo "=== FR-10.4: Validating workflow: $(basename "$WORKFLOW_FILE") ==="

# YAML syntax check FIRST — catches broken files before C1-C8 checks
if ! python3 -c "
import yaml, sys
try:
    yaml.safe_load(open(sys.argv[1]))
except yaml.YAMLError as e:
    print(str(e), file=sys.stderr)
    sys.exit(1)
" "$WORKFLOW_FILE" 2>/tmp/yaml_error.txt; then
    echo "✗ YAML SYNTAX ERROR — workflow will never parse on GitHub Actions"
    cat /tmp/yaml_error.txt
    exit 1
fi

# Run initial validation
if bash "$VALIDATOR_PATH" "$WORKFLOW_FILE" > /tmp/validation_output.txt 2>&1; then
    echo "✓ Validation passed (no fixes needed)"
    cat /tmp/validation_output.txt
    exit 0
fi

# Check if validation output contains fixable violations
VALIDATION_OUTPUT=$(cat /tmp/validation_output.txt)

# CRIT-003: C2 violations are REPORTED but NOT auto-fixed.
# Auto-converting "if: secrets.X != ''" to "continue-on-error: true" silently
# removes the security guard, allowing the step to run unconditionally. This
# is a security-relevant change that requires human review and manual fixing.
if echo "$VALIDATION_OUTPUT" | grep -qE "\[ERROR C2\]|ERROR C2"; then
    echo "=== C2 VIOLATION: MANUAL FIX REQUIRED ==="
    echo "ERROR: C2 violation detected — secrets.* in if: condition."
    echo "ERROR: C2 violations must be fixed manually — auto-fix is disabled for safety."
    echo "ERROR: Replacing a secret guard with continue-on-error:true removes the security check."
    echo "ERROR: Please remove the secrets.* condition from if: in the affected step."
    # Print the original validation output so callers can see the exact violation
    echo "$VALIDATION_OUTPUT"
fi

if echo "$VALIDATION_OUTPUT" | grep -q "ERROR C5"; then
    echo "⚠ Detected C5 violations (bare git push) - applying auto-fix..."

    # CRIT-004: Atomic write pattern — write to tmpfile, then rename
    # Auto-fix C5: Add fallback to bare git push commands
    python3 - "$WORKFLOW_FILE" << 'PYEOF'
import re
import sys
import tempfile
import os

workflow_file = sys.argv[1]

with open(workflow_file, 'r') as f:
    lines = f.readlines()

fixed_lines = []
for line in lines:
    # Check if this is a bare git push line
    if re.search(r'^\s+git push(\s|$)', line) and '||' not in line:
        # Add fallback
        fixed_line = line.rstrip() + ' || echo "skipped - protected branch"\n'
        fixed_lines.append(fixed_line)
    else:
        fixed_lines.append(line)

# Atomic write: write to tmpfile in same directory, then rename
workflow_dir = os.path.dirname(os.path.abspath(workflow_file))
tmp_fd, tmp_path = tempfile.mkstemp(dir=workflow_dir, suffix='.tmp')
try:
    with os.fdopen(tmp_fd, 'w') as tmp_f:
        tmp_f.writelines(fixed_lines)
    os.rename(tmp_path, workflow_file)
except Exception:
    os.unlink(tmp_path)
    raise

print(f"✓ C5 auto-fix applied to {workflow_file}")
PYEOF
fi

# Re-validate after fixes
echo ""
echo "=== Re-validating after auto-fixes ==="
if bash "$VALIDATOR_PATH" "$WORKFLOW_FILE"; then
    echo ""
    echo "✓ Auto-fixes successful - workflow now passes validation"
    exit 0
else
    echo ""
    echo "✗ Unfixable violations remain - manual intervention required"
    bash "$VALIDATOR_PATH" "$WORKFLOW_FILE" || true
    exit 1
fi
