#!/usr/bin/env bash
# =============================================================================
# validate-and-fix-workflow.sh — FR-10.4 Autonomous Agent Workflow Validation
# =============================================================================
# Validates workflows generated by autonomous agents and applies auto-fixes
# for common violations (C2: secrets in if, C5: bare git push).
#
# Usage:
#   ./scripts/validate-and-fix-workflow.sh <workflow-file>
#
# Exit codes:
#   0 = pass (validated successfully, with or without fixes)
#   1 = fail (unfixable violations remain)
#   2 = warnings only (no errors)
#
# Auto-fix coverage:
#   - C2: secrets.* in if: → replace with continue-on-error: true
#   - C5: bare git push → add || echo "skipped - protected branch"
#
# Other constraints escalate to blocked (manual intervention required).
# =============================================================================

set -uo pipefail

WORKFLOW_FILE="$1"
VALIDATOR_PATH="/home/ladmin/seven-fortunas-workspace/7f-infrastructure-project/scripts/validate-workflow-compliance.sh"

if [[ ! -f "$WORKFLOW_FILE" ]]; then
    echo "Error: Workflow file not found: $WORKFLOW_FILE"
    exit 1
fi

if [[ ! -f "$VALIDATOR_PATH" ]]; then
    echo "Error: Validator not found: $VALIDATOR_PATH"
    exit 1
fi

echo "=== FR-10.4: Validating workflow: $(basename "$WORKFLOW_FILE") ==="

# Run initial validation
if bash "$VALIDATOR_PATH" "$WORKFLOW_FILE" > /tmp/validation_output.txt 2>&1; then
    echo "✓ Validation passed (no fixes needed)"
    cat /tmp/validation_output.txt
    exit 0
fi

# Check if validation output contains fixable violations
VALIDATION_OUTPUT=$(cat /tmp/validation_output.txt)

if echo "$VALIDATION_OUTPUT" | grep -q "ERROR C2"; then
    echo "⚠ Detected C2 violations (secrets in if:) - applying auto-fix..."

    # Auto-fix C2: Comment out secret-conditional if: lines and add continue-on-error
    python3 - "$WORKFLOW_FILE" << 'PYEOF'
import re
import sys

workflow_file = sys.argv[1]

with open(workflow_file, 'r') as f:
    lines = f.readlines()

fixed_lines = []
i = 0
while i < len(lines):
    line = lines[i]
    # Check if this is an if: line with secrets.*
    if re.match(r'^\s+if:\s+.*secrets\.', line):
        indent = len(line) - len(line.lstrip())
        # Comment out the if: line
        fixed_lines.append(f"{' ' * indent}# {line.lstrip()}# Auto-fixed C2: replaced with continue-on-error\n")
        # Add continue-on-error instead
        fixed_lines.append(f"{' ' * indent}continue-on-error: true\n")
    else:
        fixed_lines.append(line)
    i += 1

with open(workflow_file, 'w') as f:
    f.writelines(fixed_lines)

print(f"✓ C2 auto-fix applied")
PYEOF
fi

if echo "$VALIDATION_OUTPUT" | grep -q "ERROR C5"; then
    echo "⚠ Detected C5 violations (bare git push) - applying auto-fix..."

    # Auto-fix C5: Add fallback to bare git push commands
    python3 << 'PYEOF'
import re
import sys

workflow_file = sys.argv[1]

with open(workflow_file, 'r') as f:
    lines = f.readlines()

fixed_lines = []
for line in lines:
    # Check if this is a bare git push line
    if re.search(r'^\s+git push(\s|$)', line) and '||' not in line:
        # Add fallback
        fixed_line = line.rstrip() + ' || echo "skipped - protected branch"\n'
        fixed_lines.append(fixed_line)
    else:
        fixed_lines.append(line)

with open(workflow_file, 'w') as f:
    f.writelines(fixed_lines)

print(f"✓ C5 auto-fix applied to {workflow_file}")
PYEOF
    python3 -c "import sys; sys.argv.append('$WORKFLOW_FILE')" "$WORKFLOW_FILE"
fi

# Re-validate after fixes
echo ""
echo "=== Re-validating after auto-fixes ==="
if bash "$VALIDATOR_PATH" "$WORKFLOW_FILE"; then
    echo ""
    echo "✓ Auto-fixes successful - workflow now passes validation"
    exit 0
else
    echo ""
    echo "✗ Unfixable violations remain - manual intervention required"
    bash "$VALIDATOR_PATH" "$WORKFLOW_FILE" || true
    exit 1
fi
