#!/usr/bin/env bash
# =============================================================================
# validate-and-fix-workflow.sh — FR-10.4 Autonomous Agent Workflow Validation
# =============================================================================
# Validates workflows generated by autonomous agents and applies auto-fixes
# for common violations (C5: bare git push).
#
# Usage:
#   ./scripts/validate-and-fix-workflow.sh <workflow-file>
#
# Exit codes:
#   0 = pass (validated successfully, with or without fixes)
#   1 = fail (unfixable violations remain)
#   2 = warnings only (no errors)
#
# Auto-fix coverage:
#   - C5: bare git push → add || echo "skipped - protected branch"
#
# NOT auto-fixed:
#   - C2a: ${{ secrets.X }} in run: shell blocks → REPORTED as error, never auto-fixed.
#     Risk: expression injection — secret value interpolated into shell before execution.
#     Fix: move to env: block and reference via $ENV_VAR.
#   - C2b: if: secrets.X != '' in step conditions → WARNING only (not an error).
#     Risk: code smell — secret presence/absence visible in UI. Not injection.
#     Fix: move to if: env.X != '' with env: block (optional — does not block CI).
#
# Other constraints escalate to blocked (manual intervention required).
# =============================================================================

set -uo pipefail

WORKFLOW_FILE="$1"

# MED-002: Use SCRIPT_DIR-relative path instead of hardcoded absolute path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VALIDATOR_PATH="$SCRIPT_DIR/validate-workflow-compliance.sh"

if [[ ! -f "$WORKFLOW_FILE" ]]; then
    echo "Error: Workflow file not found: $WORKFLOW_FILE"
    exit 1
fi

if [[ ! -f "$VALIDATOR_PATH" ]]; then
    echo "Error: Validator not found: $VALIDATOR_PATH"
    exit 1
fi

echo "=== FR-10.4: Validating workflow: $(basename "$WORKFLOW_FILE") ==="

# YAML syntax check FIRST — catches broken files before C1-C8 checks
if ! python3 -c "
import yaml, sys
try:
    yaml.safe_load(open(sys.argv[1]))
except yaml.YAMLError as e:
    print(str(e), file=sys.stderr)
    sys.exit(1)
" "$WORKFLOW_FILE" 2>/tmp/yaml_error.txt; then
    echo "✗ YAML SYNTAX ERROR — workflow will never parse on GitHub Actions"
    cat /tmp/yaml_error.txt
    exit 1
fi

# Run initial validation
if bash "$VALIDATOR_PATH" "$WORKFLOW_FILE" > /tmp/validation_output.txt 2>&1; then
    echo "✓ Validation passed (no fixes needed)"
    cat /tmp/validation_output.txt
    exit 0
fi

# Check if validation output contains fixable violations
VALIDATION_OUTPUT=$(cat /tmp/validation_output.txt)

# CRIT-003: C2a violations (expression injection) are REPORTED but NOT auto-fixed.
# ${{ secrets.X }} in run: blocks interpolates the secret value into the shell
# before execution — this is an injection risk. Fix: move to env: block.
# C2b violations (if: secrets.X) are warnings only — they do not trigger this block.
if echo "$VALIDATION_OUTPUT" | grep -qE "\[ERROR C2\]|C2a:"; then
    echo "=== C2a VIOLATION: MANUAL FIX REQUIRED ==="
    echo "ERROR: \${{ secrets.X }} expression found in a run: shell block."
    echo "ERROR: Move secrets to an env: block and reference via \$ENV_VAR_NAME."
    echo "ERROR: Example fix:"
    echo "ERROR:   env:"
    echo "ERROR:     MY_SECRET: \${{ secrets.MY_SECRET }}"
    echo "ERROR:   run: |"
    echo "ERROR:     use_tool --key \"\$MY_SECRET\""
    # Print the original validation output so callers can see the exact violation
    echo "$VALIDATION_OUTPUT"
fi

if echo "$VALIDATION_OUTPUT" | grep -q "ERROR C5"; then
    echo "⚠ Detected C5 violations (bare git push) - applying auto-fix..."

    # CRIT-004: Atomic write pattern — write to tmpfile, then rename
    # Auto-fix C5: Add fallback to bare git push commands
    python3 - "$WORKFLOW_FILE" << 'PYEOF'
import re
import sys
import tempfile
import os

workflow_file = sys.argv[1]

with open(workflow_file, 'r') as f:
    lines = f.readlines()

fixed_lines = []
for line in lines:
    # Check if this is a bare git push line
    if re.search(r'^\s+git push(\s|$)', line) and '||' not in line:
        # Add fallback
        fixed_line = line.rstrip() + ' || echo "skipped - protected branch"\n'
        fixed_lines.append(fixed_line)
    else:
        fixed_lines.append(line)

# Atomic write: write to tmpfile in same directory, then rename
workflow_dir = os.path.dirname(os.path.abspath(workflow_file))
tmp_fd, tmp_path = tempfile.mkstemp(dir=workflow_dir, suffix='.tmp')
try:
    with os.fdopen(tmp_fd, 'w') as tmp_f:
        tmp_f.writelines(fixed_lines)
    os.rename(tmp_path, workflow_file)
except Exception:
    os.unlink(tmp_path)
    raise

print(f"✓ C5 auto-fix applied to {workflow_file}")
PYEOF
fi

# Re-validate after fixes
echo ""
echo "=== Re-validating after auto-fixes ==="
if bash "$VALIDATOR_PATH" "$WORKFLOW_FILE"; then
    echo ""
    echo "✓ Auto-fixes successful - workflow now passes validation"
    exit 0
else
    echo ""
    echo "✗ Unfixable violations remain - manual intervention required"
    bash "$VALIDATOR_PATH" "$WORKFLOW_FILE" || true
    exit 1
fi
